import json
import sys
import string
import pywikibot

#Data is automatically copied to the wiki template pages.
#Usage: python [location of pywikibotinstall]\pwb.py bionicsList.py
#   Then input your password, and wait for the pages to be updated.

with open('data/json/bionics.json') as data_file:
    data = json.load(data_file)

with open('data/json/items/bionics.json') as data_file:
    data1 = json.load(data_file)

ID_bionic = list()
ID_bionic_faulty = list()
for iterator in range(0, len(data)):
    if('flags' in data[iterator]):
        if('BIONIC_FAULTY' in data[iterator]['flags']): #only add bionics that are not faulty to this list.
            ID_bionic_faulty.append(data[iterator]["name"])
        else:
            ID_bionic.append(data[iterator]["name"])
    else:
        ID_bionic.append(data[iterator]["name"])

for iterator in range(0, len(data1)): #the previous loop does not add some cbms, this loop will add the missing ones.
    if(not 'abstract' in data1[iterator]): #don't add abstract bionics.
        excluded = True
        for iter in range(0, len(data)):
            if(data[iter]['id'] == data1[iterator]['id']):
                excluded = False
                break
        if(excluded):
            ID_bionic.append(data1[iterator]["name"])

ID_bionic = sorted(ID_bionic, key=string.lower) 
ID_bionic_faulty = sorted(ID_bionic_faulty, key=string.lower) 

output = [ "" ]
output_faulty = [ "" ]
footer = '''
<noinclude>Automatically generated by [https://github.com/Soyweiser/CDDA-Wiki-Scripts The bionicsList.py script]. Any edits made to this can and will be overwritten. Please contact [[User:Soyweiser|Soyweiser]] if you want make changes to this page. Especially as any changes made here probably also means there have been changes in other pages. And there are tools to update those a little bit quicker.\n
[[Category:Templates]]\n
</noinclude>'''
output.append("{{header/Bionics}}\n")
output_faulty.append("{{header/FaultyBionics}}\n")
output.append("<!--Automatically generated using https://github.com/Soyweiser/CDDA-Wiki-Scripts -->\n\n")
output_faulty.append("<!--Automatically generated using https://github.com/Soyweiser/CDDA-Wiki-Scripts -->\n\n")
for it in range(0, len(ID_bionic)):
    output.append("{{:")
    output.append(ID_bionic[it])
    output.append("}}\n")
for it in range(0, len(ID_bionic_faulty)):
    output_faulty.append("{{:")
    output_faulty.append(ID_bionic_faulty[it])
    output_faulty.append("}}\n")
output.append("</table>\n")
output.append(footer)
output_faulty.append("</table>\n")
output_faulty.append(footer)


text = "".join(output)
text.replace("\n", "\\n")
faultytext = "".join(output_faulty)
faultytext.replace("\n", "\\n")
site = pywikibot.Site('en', 'cddawiki')
page = pywikibot.Page(site, 'Template:List/bionics')
page.text = text
page.save('Updated text automatically via the https://github.com/Soyweiser/CDDA-Wiki-Scripts bionicsList.py script')
page = pywikibot.Page(site, 'Template:List/faultybionics')
page.text = faultytext
page.save('Updated text automatically via the https://github.com/Soyweiser/CDDA-Wiki-Scripts bionicsList.py script')
exit()