import json
import sys
import pywikibot
from version import version
from name_hacks import trait_name

#Data is automatically copied to the wiki template page.
#Usage: python [location of pywikibotinstall]\pwb.py navbar_trait.py
#   Then input your password, and wait for the page to be updated.

with open('data/json/mutations/mutations.json') as data_file:
    data = json.load(data_file)

output = [ """<noinclude><!--Automatically generated by https://github.com/Soyweiser/CDDA-Wiki-Scripts-->\n
Automatically generated by [https://github.com/Soyweiser/CDDA-Wiki-Scripts The navbar_trait.py script]. Any edits made to this can and will be overwritten. Please contact [[User:Soyweiser|Soyweiser]] if you want make changes to this page. Especially as any changes made here probably also means there have been changes in the traits and mutations pages. And there are tools to update those a little bit quicker.\n""" ]
output.append(version)
output.append("""</noinclude>
{{Navbox
|name       = Traits
|title      = [[Traits]]
|state      = uncollapsed

|bodystyle = background:white; width:100%; vertical-align:middle; border-color: #CCAAAA;
|titlestyle = background:LightGreen; color:darkblue; padding-left:1em; padding-right:1em; text-align:center;
|groupstyle = background:LightGreen; color:black; padding-left:1em; padding-right:1em; text-align:right; font-weight: bold;

  
|group1     = Positive
|list1      = <!--""")

ID_mut = dict()
for iterator in range(0, len(data)): #fill the ID_mut dictionary with 'id' data, and fill the types lists.
    keyD = dict()
    keyD['id_nr'] = iterator
    keyD["name"] = data[iterator]["name"]["str"]
    ID_mut[data[iterator]["id"]] = keyD

def ID_To_String(id): #Use the name_hacks.py file for some name hacks.
    retval = trait_name (id)
    if (retval == id):
        return ID_mut[id]["name"]
    else:
        return retval

Ptraits = list()
Ntraits = list()
Professions = list()

for iterator in range(0, len(data)):
    name = ID_To_String(data[iterator]["id"])
    if(not "player_display" in data[iterator]):
        if(not "debug" in data[iterator]):
            if("starting_trait" in data[iterator]):
                if(int(data[iterator]['points']) > 0):
                    Ptraits.append(name)
                elif(int(data[iterator]['points']) < 0):
                    Ntraits.append(name)
            if("profession" in data[iterator]):
                Professions.append(name)

Ptraits = sorted(Ptraits)
Ntraits = sorted(Ntraits)
Professions = sorted(Professions)

for it in range(0, len(Ptraits)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Ptraits[it])
    output.append("]]<!--\n")
output.append("""	-->

|group2     = Negative
|list2      = <!--\n""")

for it in range(0, len(Ntraits)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Ntraits[it])
    output.append("]]<!--\n")
output.append("""	-->

|group3     = Professions
|list3      = <!--\n""")

for it in range(0, len(Professions)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Professions[it])
    output.append("]]<!--\n")
output.append("""	-->

}}<noinclude>
[[Category:Navigational templates]][[Category:Templates]]
</noinclude>""")

text = "".join(output)
text.replace("\n", "\\n")
site = pywikibot.Site('en', 'cddawiki')
page = pywikibot.Page(site, 'Template:Navbar/traits')
page.text = text
page.save('Updated text automatically via the https://github.com/Soyweiser/CDDA-Wiki-Scripts navbar_trait.py script')
exit()