import json
import sys
from pprint import pprint
from Tkinter import Tk
root = Tk()
root.withdraw()

#Data is copied to clipboard, used for the Template:Navbar/traits

with open('data/json/mutations.json') as data_file:    
    data = json.load(data_file)

output = [ """<noinclude><!--Automatically generated by https://github.com/Soyweiser/CDDA-Wiki-Scripts--></noinclude>
{{Navbox
|name       = Traits
|title      = [[Traits]]
|state      = uncollapsed

|bodystyle = background:white; width:100%; vertical-align:middle; border-color: #CCAAAA;
|titlestyle = background:LightGreen; color:darkblue; padding-left:1em; padding-right:1em; text-align:center;
|groupstyle = background:LightGreen; color:black; padding-left:1em; padding-right:1em; text-align:right; font-weight: bold;

  
|group1     = Positive
|list1      = <!--"""]

def ID_To_WikiString(id):
    if id == "Infrared Vision":
        return "Infrared Vision (Mutation)|Infrared Vision"
    return id

Ptraits = list()
Ntraits = list()
Professions = list()

for iterator in range(0, len(data)):
    if("starting_trait" in data[iterator]):
        if(int(data[iterator]['points']) > 0):
            Ptraits.append(data[iterator]['name'])
        elif(int(data[iterator]['points']) < 0):
            Ntraits.append(data[iterator]['name'])
    if("profession" in data[iterator]):
        Professions.append(data[iterator]['name'])

Ptraits = sorted(Ptraits)
Ntraits = sorted(Ntraits)
Professions = sorted(Professions)

for it in range(0, len(Ptraits)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Ptraits[it])
    output.append("]]<!--\n")
output.append("""	-->

|group2     = Negative
|list2      = <!--\n""")

for it in range(0, len(Ntraits)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Ntraits[it])
    output.append("]]<!--\n")
output.append("""	-->

|group3     = Professions
|list3      = <!--\n""")

for it in range(0, len(Professions)):
    output.append("        --> ")
    if it > 0:
        output.append("{{md}}")
    output.append("[[")
    output.append(Professions[it])
    output.append("]]<!--\n")
output.append("""	-->

}}<noinclude>
[[Category:Navigational templates]]
</noinclude>""")
    
text = "".join(output)
text.replace("\n", "\\n")
print text
root.clipboard_clear()
root.clipboard_append(text)
root.update()
root.destroy()
exit()